// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mock struct {
	ID             pgtype.UUID
	UserID         string
	Method         string
	Path           string
	ResponseStatus int32
	ResponseBody   string
	HitCount       int32
	CreatedAt      pgtype.Timestamp
	ExpiresAt      pgtype.Timestamp
}
