// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMock = `-- name: CreateMock :one
INSERT INTO mocks (id, user_id, method, path, response_status, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, method, path, response_status, response_body, hit_count, created_at, expires_at
`

type CreateMockParams struct {
	ID             pgtype.UUID
	UserID         string
	Method         string
	Path           string
	ResponseStatus int32
	ResponseBody   string
	ExpiresAt      pgtype.Timestamp
}

func (q *Queries) CreateMock(ctx context.Context, arg CreateMockParams) (Mock, error) {
	row := q.db.QueryRow(ctx, createMock,
		arg.ID,
		arg.UserID,
		arg.Method,
		arg.Path,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	var i Mock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.HitCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpired = `-- name: DeleteExpired :exec
DELETE FROM mocks
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpired)
	return err
}

const deleteMock = `-- name: DeleteMock :exec
DELETE FROM mocks
WHERE id = $1
`

func (q *Queries) DeleteMock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMock, id)
	return err
}

const getMock = `-- name: GetMock :one
SELECT id, user_id, method, path, response_status, response_body, hit_count, created_at, expires_at FROM mocks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMock(ctx context.Context, id pgtype.UUID) (Mock, error) {
	row := q.db.QueryRow(ctx, getMock, id)
	var i Mock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.HitCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMockByPathAndMethod = `-- name: GetMockByPathAndMethod :one
SELECT id, user_id, method, path, response_status, response_body, hit_count, created_at, expires_at FROM mocks
WHERE user_id = $1 AND path = $2 AND method = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetMockByPathAndMethodParams struct {
	UserID string
	Path   string
	Method string
}

func (q *Queries) GetMockByPathAndMethod(ctx context.Context, arg GetMockByPathAndMethodParams) (Mock, error) {
	row := q.db.QueryRow(ctx, getMockByPathAndMethod, arg.UserID, arg.Path, arg.Method)
	var i Mock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.HitCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const incrementHitCount = `-- name: IncrementHitCount :exec
UPDATE mocks
SET hit_count = hit_count + 1
WHERE id = $1
`

func (q *Queries) IncrementHitCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementHitCount, id)
	return err
}

const listMocksByUser = `-- name: ListMocksByUser :many
SELECT id, user_id, method, path, response_status, response_body, hit_count, created_at, expires_at FROM mocks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMocksByUser(ctx context.Context, userID string) ([]Mock, error) {
	rows, err := q.db.Query(ctx, listMocksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mock
	for rows.Next() {
		var i Mock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Method,
			&i.Path,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.HitCount,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMock = `-- name: UpdateMock :one
UPDATE mocks
SET method = $3, path = $4, response_status = $5, response_body = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, method, path, response_status, response_body, hit_count, created_at, expires_at
`

type UpdateMockParams struct {
	ID             pgtype.UUID
	UserID         string
	Method         string
	Path           string
	ResponseStatus int32
	ResponseBody   string
}

func (q *Queries) UpdateMock(ctx context.Context, arg UpdateMockParams) (Mock, error) {
	row := q.db.QueryRow(ctx, updateMock,
		arg.ID,
		arg.UserID,
		arg.Method,
		arg.Path,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var i Mock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.HitCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
